---
title: "Introduction to carbon component estimation with `deconvolve`"
output: 
  html_document:
    css: deconvolve.css
    theme: lumen
    toc: yes
    toc_float:
      collapsed: no
      toc_depth: 4
    fig_caption: yes
vignette: >
  %\VignetteIndexEntry{Introduction to carbon component estimation with `deconvolve`}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Mixture model

The meat of this package is in the mixture model used to deconvolve the derivative rate curve. Many different mathematical models have been proposed to fit the form of the independent curves, including Gassian, Lorentzian, Weibull, the asymmetric bi-Gaussian, and the Frazer-Suzuki distributions. Symmetric curves such as the Gaussian and Lorentzian curves struggle to model these kinetic curves because they are often asymmetric. The four-parameter Fraser-Suzuki function is highly flexible and therefore performs well. 

\begin{equation}
\frac{d\alpha_i}{dT} = h_i\ exp\bigg\{-\frac{ln2}{s_i^2}\Big[ln\Big(1 + 2s_i \frac{T - p_i}{w_i}\Big)\Big]^2\bigg\}
\end{equation}


Because we can assume that the carbon components decay relatively independently, we can thus model the full multi-peaked derivative rate of mass loss curve as the sum of independent Fraser-Suzuki curves. You can play around with changing individual parameters for each curve, and check out the effect on the overall decay curve, using the [shiny app](https://smwindecker.shinyapps.io/deconvolve/). 

<hr>

