#' Sets default plotting for process objects
#'
#' This function sets up the default plotting method
#' for outputs from process function
#'
#' @param x process object as generated by process
#' @param plot_type defaults to both plots. Can specify 'mass' or 'rate' curves by themselves.
#' @param ... other options passed to plot
#' @return plot
#' @method plot process
#' @importFrom graphics legend lines par plot
#'
#' @export

plot.process <- function (x, plot_type = NULL, ...) {

  df <- x$data

  p_massloss <- function (data) {
    plot(data$temp_C, data$mass_T, xlab = 'Temperature (C)',
         ylab = 'Mass Remaining (mg)', pch = 20, cex = 0.7)
  }

  p_dtg <- function (data) {
    plot(data$temp_C, data$deriv, xlab = 'Temperature (C)',
         ylab = expression(paste('Rate of mass loss (-dm/dT) (C'^'-1', ')')),
         pch = 20, cex = 0.7)
  }

  if (plot_type == 'mass') {
    p_massloss(df)
  }
  if (plot_type == 'rate') {
    p_dtg(df)
  }
  if (is.null(plot_type)) {
    par(mfrow = c(1,2), mar = c(5, 5, 1, 1))
    p_massloss(df)
    p_dtg(df)
  }

}
