#' Sets default plotting for process objects
#'
#' This function sets up the default plotting method
#' for outputs from process function
#'
#' @param x process object as generated by process
#' @param plot_type defaults to dtg plot. Can choose 'mass_loss', 'both'.
#' @param ... other options passed to plot
#' @return plot
#' @import pryr
#' @method plot process
#' @importFrom graphics legend lines par plot
#'
#' @export

### need to make so if plot window too small it automatically pops up in pop up?
### otherwise just get 'error in plot.new() : figure margins too large'

plot.process <- function (x, plot_type = NULL, ...) {

  df <- x$data

  p_massloss <- function (data) {
    plot(data$temp_K, data$mass_T, xlab = 'Temperature (K)', ylab = 'Mass Remaining (mg)')
  }

  p_dtg <- function (data) {
    plot(data$temp_K, data$deriv, xlab = 'Temperature (K)', ylab = 'DTG (dm/dT) (K-1)')
  }

  p_both <- function (data) {
    par(mfrow=c(1,2))
    plot(data$temp_K, data$mass_T, xlab = 'Temperature (K)', ylab = 'Mass Remaining (mg)')
    plot(data$temp_K, data$deriv, xlab = 'Temperature (K)', ylab = 'DTG (dm/dT) (K-1)')
  }

  if (!is.null(plot_type) && plot_type == 'mass_loss') {
    p_massloss(df)
  } else if (!is.null(plot_type) && plot_type == 'both') {
    p_both(df)
  } else {
    p_dtg(df)
  }

}

