#' Default S3 print method for process object (derived from `process()`)
#'
#' This function sets up the default print method
#' for outputs from process function
#'
#' @param x process object as generated by deconvolve
#' @param ... other options passed to plot
#' @return print output
#' @method print process
#'
#' @export

print.process <- function (x, ...) {

  cat(paste('Derivative thermogravimetry data (DTG)
            calculated for\n', nrow(x$data), 'datapoints from',
            round(x$bounds[1], 2), 'to',
            round(x$bounds[2], 2), 'degrees C.'))

}

