#' Sets default print method for process object
#'
#' This function sets up the default print method
#' for outputs from process function
#'
#' @param x process object as generated by deconvolve
#' @param ... other options passed to plot
#' @return print output
#' @method print process
#'
#' @export

print.process <- function (x, ...) {

  cat(paste('Derivative thermogravimetry data (DTG) calculated for',
             nrow(x$data), 'datapoints from', x$bounds[1],
            'to', x$bounds[2], 'degrees C.'))

}
