name: Build R-WASM binaries

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and upload WASM binaries
        uses: r-wasm/actions@v1
        with:
          packages: "."
          repo-token: ${{ secrets.GITHUB_TOKEN }}
